# https://travis-ci.org/minghu6/ordered-set
language: python
python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
script: nosetests
sudo: false
notifications:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

